-- NKKSmart blank-install schema template.
-- Use only on a NEW Supabase project. This creates structure only and inserts
-- no members, meetings, attendance, admin accounts, or geofence coordinates.
-- It is intentionally non-destructive: there are no DROP/TRUNCATE statements.
-- After this file, run nkksmart_all_changes.sql for registration, reports,
-- leaderboard, card lookup, app settings, and their RPCs/policies.

begin;

create table if not exists public.admins (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  full_name text not null,
  last_login timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.anggota (
  id bigint generated by default as identity primary key,
  kode_qr text unique,
  nama_lengkap text not null,
  kelas text not null default '',
  jurusan text not null default '',
  nis text,
  jenis_kelamin text,
  jabatan text not null default 'Anggota',
  status text not null default 'Aktif',
  is_deleted boolean not null default false,
  tampil_leaderboard boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.barcode (
  id bigint generated by default as identity primary key,
  anggota_id bigint not null references public.anggota(id) on delete cascade,
  kode_unik text not null unique,
  qr_value text not null,
  created_at timestamptz not null default now(),
  constraint barcode_anggota_id_key unique (anggota_id)
);

create table if not exists public.pertemuan (
  id bigint generated by default as identity primary key,
  nama_pertemuan text not null,
  pertemuan_ke integer not null,
  tanggal date not null,
  jam_mulai_scan time not null default '15:30',
  jam_akhir_scan time not null default '17:30',
  manual_active boolean not null default false,
  is_libur boolean not null default false,
  keterangan text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.absensi (
  id bigint generated by default as identity primary key,
  pertemuan_id bigint not null references public.pertemuan(id) on delete cascade,
  anggota_id bigint not null references public.anggota(id) on delete cascade,
  barcode_id bigint references public.barcode(id) on delete set null,
  status text not null default 'hadir',
  source text not null default 'manual',
  scan_time timestamptz not null default now(),
  waktu_scan timestamptz not null default now(),
  catatan text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint absensi_pertemuan_anggota_key unique (pertemuan_id, anggota_id)
);

create table if not exists public.geofence_settings (
  id smallint primary key check (id = 1),
  lat double precision,
  lng double precision,
  radius integer not null default 600 check (radius > 0),
  updated_at timestamptz not null default now(),
  constraint geofence_coordinates_pair check ((lat is null) = (lng is null)),
  constraint geofence_lat_range check (lat is null or lat between -90 and 90),
  constraint geofence_lng_range check (lng is null or lng between -180 and 180)
);

create table if not exists public.app_settings (
  key text primary key,
  value jsonb not null
);

create index if not exists anggota_active_lookup_idx
  on public.anggota(status, is_deleted, jabatan, kelas, nama_lengkap);
create index if not exists barcode_code_lookup_idx on public.barcode(kode_unik);
create index if not exists pertemuan_date_lookup_idx on public.pertemuan(tanggal desc, pertemuan_ke desc);
create index if not exists absensi_meeting_lookup_idx on public.absensi(pertemuan_id, anggota_id);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (select 1 from public.admins a where a.id = auth.uid());
$$;

create or replace function public.get_geofence()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((
    select jsonb_build_object(
      'configured', g.lat is not null and g.lng is not null,
      'lat', g.lat, 'lng', g.lng, 'radius', g.radius,
      'message', case when g.lat is null then 'Lokasi belum dikonfigurasi.' else 'Geofence aktif.' end
    )
    from public.geofence_settings g where g.id = 1
  ), jsonb_build_object('configured', false, 'radius', 600, 'message', 'Lokasi belum dikonfigurasi.'));
$$;

create or replace function public.get_scan_status()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  meeting_row public.pertemuan%rowtype;
  local_now timestamp := now() at time zone 'Asia/Jakarta';
  meeting_is_open boolean;
  result_status text;
begin
  select * into meeting_row
  from public.pertemuan p
  where p.manual_active or p.tanggal <= local_now::date
  order by p.tanggal desc, p.pertemuan_ke desc, p.id desc
  limit 1;

  if not found then
    return jsonb_build_object('active', false, 'status', 'no_meeting', 'meeting', null,
      'message', 'Belum ada pertemuan.');
  end if;

  meeting_is_open := meeting_row.manual_active or
    (meeting_row.tanggal = local_now::date and local_now::time between meeting_row.jam_mulai_scan and meeting_row.jam_akhir_scan);
  if meeting_row.is_libur then result_status := 'libur';
  elsif meeting_row.manual_active then result_status := 'manual';
  elsif meeting_is_open then result_status := 'active';
  else result_status := 'inactive';
  end if;

  return jsonb_build_object(
    'active', meeting_is_open and not meeting_row.is_libur,
    'status', result_status,
    'meeting', jsonb_build_object(
      'id', meeting_row.id, 'nama_pertemuan', meeting_row.nama_pertemuan,
      'pertemuan_ke', meeting_row.pertemuan_ke, 'tanggal', meeting_row.tanggal,
      'jam_mulai_scan', meeting_row.jam_mulai_scan, 'jam_akhir_scan', meeting_row.jam_akhir_scan,
      'manual_active', meeting_row.manual_active, 'status', result_status
    ),
    'message', case when meeting_row.is_libur then 'Pertemuan diliburkan.'
      when meeting_is_open then 'Presensi sedang dibuka.' else 'Presensi belum dibuka.' end
  );
end;
$$;

create or replace function public.submit_scan(kode text, scan_type text default 'auto', mode text default 'camera')
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  meeting_row public.pertemuan%rowtype;
  member_row public.anggota%rowtype;
  barcode_row public.barcode%rowtype;
  local_now timestamp := now() at time zone 'Asia/Jakarta';
  attendance_id bigint;
begin
  if nullif(btrim(coalesce(kode, '')), '') is null then
    return jsonb_build_object('ok', false, 'message', 'Kode kartu kosong.');
  end if;
  if scan_type not in ('auto', 'anggota', 'pengurus') or mode not in ('camera', 'manual') then
    return jsonb_build_object('ok', false, 'message', 'Jenis presensi tidak valid.');
  end if;

  select * into meeting_row from public.pertemuan p
  where (p.manual_active or p.tanggal <= local_now::date) and not p.is_libur
    and (p.manual_active or (p.tanggal = local_now::date and local_now::time between p.jam_mulai_scan and p.jam_akhir_scan))
  order by p.tanggal desc, p.pertemuan_ke desc, p.id desc limit 1;
  if not found then return jsonb_build_object('ok', false, 'message', 'Presensi belum dibuka.'); end if;

  select * into barcode_row from public.barcode b
  where lower(btrim(b.kode_unik)) = lower(btrim(kode)) or b.qr_value = btrim(kode)
  limit 1;
  if not found then
    select * into member_row from public.anggota a where lower(btrim(a.kode_qr)) = lower(btrim(kode)) limit 1;
  else
    select * into member_row from public.anggota a where a.id = barcode_row.anggota_id;
  end if;
  if not found or member_row.status <> 'Aktif' or coalesce(member_row.is_deleted, false) then
    return jsonb_build_object('ok', false, 'message', 'Kartu atau anggota tidak ditemukan/aktif.');
  end if;
  if scan_type = 'anggota' and member_row.jabatan <> 'Anggota' then
    return jsonb_build_object('ok', false, 'message', 'Kartu ini bukan kartu anggota.');
  elsif scan_type = 'pengurus' and member_row.jabatan <> 'Pengurus' then
    return jsonb_build_object('ok', false, 'message', 'Kartu ini bukan kartu pengurus.');
  end if;

  insert into public.absensi(pertemuan_id, anggota_id, barcode_id, status, source, scan_time, waktu_scan, created_at, updated_at)
  values (meeting_row.id, member_row.id, barcode_row.id, 'hadir', mode, now(), now(), now(), now())
  on conflict (pertemuan_id, anggota_id) do nothing
  returning id into attendance_id;
  if attendance_id is null then
    return jsonb_build_object('ok', false, 'message', 'Sudah Absen', 'nama', member_row.nama_lengkap, 'kelas', member_row.kelas);
  end if;
  return jsonb_build_object('ok', true, 'message', 'Absensi berhasil', 'nama', member_row.nama_lengkap,
    'kelas', member_row.kelas, 'jabatan', member_row.jabatan, 'waktu_scan', now());
end;
$$;

revoke all on function public.is_admin() from public, anon;
grant execute on function public.is_admin() to authenticated;
revoke all on function public.get_geofence() from public;
grant execute on function public.get_geofence() to anon, authenticated;
revoke all on function public.get_scan_status() from public;
grant execute on function public.get_scan_status() to anon, authenticated;
revoke all on function public.submit_scan(text, text, text) from public;
grant execute on function public.submit_scan(text, text, text) to anon, authenticated;

alter table public.admins enable row level security;
alter table public.anggota enable row level security;
alter table public.barcode enable row level security;
alter table public.pertemuan enable row level security;
alter table public.absensi enable row level security;
alter table public.geofence_settings enable row level security;
alter table public.app_settings enable row level security;

revoke all on public.admins, public.anggota, public.barcode, public.pertemuan,
  public.absensi, public.geofence_settings, public.app_settings from anon, authenticated;
grant select on public.admins to authenticated;
grant select, insert, update, delete on public.anggota, public.barcode, public.pertemuan,
  public.absensi, public.geofence_settings, public.app_settings to authenticated;
grant usage, select on sequence public.anggota_id_seq, public.barcode_id_seq,
  public.pertemuan_id_seq, public.absensi_id_seq to authenticated;

drop policy if exists "Admin reads own profile" on public.admins;
create policy "Admin reads own profile" on public.admins for select to authenticated using (id = auth.uid());
drop policy if exists "Admin manages members" on public.anggota;
create policy "Admin manages members" on public.anggota for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "Admin manages barcodes" on public.barcode;
create policy "Admin manages barcodes" on public.barcode for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "Admin manages meetings" on public.pertemuan;
create policy "Admin manages meetings" on public.pertemuan for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "Admin manages attendance" on public.absensi;
create policy "Admin manages attendance" on public.absensi for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "Admin manages geofence" on public.geofence_settings;
create policy "Admin manages geofence" on public.geofence_settings for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "Admin manages app settings" on public.app_settings;
create policy "Admin manages app settings" on public.app_settings for all to authenticated using (public.is_admin()) with check (public.is_admin());

commit;

-- To bootstrap the first administrator, first create a user in Supabase Auth,
-- then run this statement in SQL Editor with that user's Auth UUID and username:
-- insert into public.admins (id, username, full_name)
-- values ('AUTH-USER-UUID', 'admin-username', 'Admin Name');
